title: CASTANER
description: CASTANER
theme: just-the-docs

url: https://github.com/espadrillesbanyoles-lautaroespinosa/Jekyll/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
  

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout
